#
# Docker
#  build:
#   docker build -t epltranslate -f Dockerfile.node .
#
#
#  run:
#   docker run -p 3000:3000 epltranslate
#


FROM node:4

MAINTAINER ReLang

ENV NODE_ENV=production
ENV PORT=3000

RUN echo "building docker container"

WORKDIR /app
COPY . /app


RUN npm install

EXPOSE $PORT

CMD ["node", "app.js"]

