version: '2'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports: 
      - 3000:3000
    environment:
      - NODE_ENV=production
    links:
      - mongodb:mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017

